version: '3.5'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=digitalsys_user
      - POSTGRES_PASSWORD=quwhdq193d17dh
      - POSTGRES_DB=digitalsys_dev

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.9-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery:
    restart: always
    build:
      context: ./digitalsys_api
    command: celery -A digitalsys_api worker -l info
    volumes:
      - .:/test_celery
    depends_on:
      - rabbitmq

  app:
    build:
      context: ./digitalsys_api
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - .:/code
    command: >
      sh -c " python digitalsys_api/manage.py migrate &&
              python digitalsys_api/manage.py loaddata proposal_fields_fixtures &&
              python digitalsys_api/manage.py loaddata user_fixtures &&
              python digitalsys_api/manage.py runserver 0.0.0.0:8181"
    depends_on:
      - celery
      - db

  web:
    build:
      context: ./digitalsys_web
      dockerfile: Dockerfile
    container_name: vite-react-express
    command: >
      sh -c " cd digitalsys_web &&
              npm install &&
              npm run dev"
    image: vite-react-express:latest
    ports:
      - '5173:5173'
    volumes:
      - .:/web

volumes:
  postgres_data:
  rabbitmq_data:
  web: