# Generated by Django 3.2.9 on 2023-06-22 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PENDING', 'Pending')], default='PENDING', max_length=12, verbose_name='Status')),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='ProposalField',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('field_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('DATE', 'Date')], default='TEXT', max_length=12, verbose_name='Field Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'db_table': 'proposal_fields',
            },
        ),
        migrations.CreateModel(
            name='ProposalFieldValue',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=255)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
                ('proposal_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalfield')),
            ],
            options={
                'db_table': 'proposal_field_values',
            },
        ),
    ]
