# Generated by Django 3.2.9 on 2023-06-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfieldvalue',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_proposal_field_value', to='proposal.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalfieldvalue',
            name='proposal_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_field_proposal_field_value', to='proposal.proposalfield'),
        ),
    ]
