# Generated by Django 3.2.9 on 2023-06-23 00:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20230623_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Id'),
        ),
        migrations.AlterField(
            model_name='proposalfield',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='proposalfield',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='proposalfield',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Id'),
        ),
        migrations.AlterField(
            model_name='proposalfieldvalue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='proposalfieldvalue',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='proposalfieldvalue',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Id'),
        ),
    ]
