# Generated by Django 3.2.9 on 2023-06-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20230623_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterModelOptions(
            name='proposalfield',
            options={'verbose_name': 'Proposal Field', 'verbose_name_plural': 'Proposal Fields'},
        ),
    ]
