# Generated by Django 3.2.9 on 2023-06-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20230623_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfield',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='proposalfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
    ]
